export const TOOL_LABELS: Record<string, string> = {
  read_skill: 'Loaded training knowledge',
  get_user_profile: 'Checked your profile',
  get_active_program: 'Got the active program',
  get_program_criteria: 'Reviewed program settings',
  propose_program: 'Created a draft program',
  confirm_program_save: 'Saved the program',
  propose_adjustment: 'Prepared adjustments',
  confirm_adjustment: 'Applied adjustments',
  update_program_criteria: 'Updated program settings',
  get_scheduled_activity: 'Checked the scheduled workout',
  get_draft_program: 'Checked for a draft',
  create_draft_program: 'Created a draft',
  save_draft_criterion: 'Saved your answer',
  modify_pending_proposal: 'Updated the program',
  propose_program_modification: 'Prepared program changes',
  confirm_program_modification: 'Applied program changes',
};
