export const TOOL_LABELS: Record<string, string> = {
  read_skill: 'Loaded training knowledge',
  get_user_profile: 'Checked your profile',
  get_active_program: 'Got the active program',
  get_program_criteria: 'Reviewed program settings',
  propose_program: 'Created a draft program',
  confirm_program_save: 'Saved the program',
  start_program_today: 'Starting your program today',
  set_weekly_effort_goal: 'Set your weekly effort goal',
  edit_program: 'Prepared program changes',
  confirm_edit: 'Applied program changes',
  get_scheduled_activity: 'Checked the scheduled workout',
  get_draft_program: 'Checked for a draft',
  create_draft_program: 'Created a draft',
  save_draft_criterion: 'Saved your answer',
  save_draft_phase: 'Saved a phase',
  update_draft_phase: 'Updated a phase',
  delete_draft_phase: 'Removed a phase',
  begin_program_creation: 'Switching to program creation',
};
